version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'    # AMQP
      - '15672:15672'  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - ./config/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped
    networks:
      - rabbitmq-net
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - postgres-net
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - redis-net
  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-gateway
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - minio-net

volumes:
  pgdata:
  redisdata:
  minio-data:

networks:
  postgres-net:
    external: true
  rabbitmq-net:
    external: true
  redis-net:
    external: true
  nginx-gateway:
    external: true
  minio-net:
    external: true


