version: '3.8'

services:
  auth-service:
      build: .
      container_name: auth-service
      environment:
        - DATABASE_URL=postgresql://admin:123123@postgres:5432/authdb
        - RABBITMQ_URL=amqp://myuser:123123@rabbitmq:5672
        - REDIS_URL=redis://redis:6379
      volumes:
        - ./:/app
      working_dir: /app
      command: sh -c "npm install && npm run start:dev"
      ports:
        - "3000:3000"
      networks:
        - postgres-net
        - rabbitmq-net
        - redis-net
        - nginx-gateway
  auth-worker:
    build:
      context: .
    container_name: auth-worker
    command: npm run start:worker
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://myuser:123123@rabbitmq:5672
    depends_on:
      - auth-service
    networks:
      - rabbitmq-net
      - postgres-net
      - redis-net
      
networks:
  postgres-net:
    external: true
  rabbitmq-net:
    external: true
  redis-net:
    external: true
  nginx-gateway:
    external: true

