version: '3.8'

services:
  verification-service:
      build: .
      container_name: verification-service
      environment:
        DATABASE_URL: ${DATABASE_URL}
        RABBITMQ_URL: ${RABBITMQ_URL}
      volumes:
        - ./:/app
      working_dir: /app
      command: sh -c "npm install && npm run start:dev"
      ports:
        - "3002:3002"
      networks:
        - postgres-net
        - rabbitmq-net
        - minio-net
        - nginx-gateway
  verification-worker:
    build: .
    container_name: verification-worker
    command: npm run start:worker
    environment:
      NODE_ENV: production
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - rabbitmq-net
      - postgres-net
      - minio-net

networks:
  postgres-net:
    external: true
  rabbitmq-net:
    external: true
  nginx-gateway:
    external: true
  minio-net:
    external: true

