version: '3.8'

services:
  user-service:
      build: .
      container_name: user-service
      environment:
        DATABASE_URL: ${DATABASE_URL}
        RABBITMQ_URL: ${RABBITMQ_URL}
      volumes:
        - ./:/app
      working_dir: /app
      command: sh -c "npm install && npm run start:dev"
      ports:
        - '3001:3001'
      networks:
        - postgres-net
        - rabbitmq-net
        - nginx-gateway
  user-worker:
    build: .
    container_name: user-worker
    command: npm run start:worker
    environment:
      NODE_ENV: production
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - rabbitmq-net
      - postgres-net
      
networks:
  postgres-net:
    external: true
  rabbitmq-net:
    external: true
  nginx-gateway:
    external: true

